sudo: false
language: node_js
node_js:
  - 6
  - 8
script:
  - APP_DIR=src scripts/create-project-symlink.sh
  - npm install
  - APP_DIR=src npm run postinstall
  - npm run lint
  - npm test
before_deploy: 'npm run prepublishOnly'
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    branch: master
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: always
