sudo: false
language: node_js
node_js:
  - 6
  - node
script:
  - npm install
  - APP_DIR=src npm run postinstall
  - npm run lint
  - npm test
notifications:
  email:
    on_success: never
    on_failure: always
